-- MySQL Script generated by MySQL Workbench
-- Wed Apr  2 10:36:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actor` (
  `Id_Actor` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Fecha_Nacimiento` DATE NULL,
  PRIMARY KEY (`Id_Actor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cine` (
  `Id_Cine` INT NOT NULL,
  `Direccion` VARCHAR(255) NULL,
  `Telefono` VARCHAR(50) NULL,
  `Ciudad` VARCHAR(100) NULL,
  `Nombre_Cine` VARCHAR(100) NULL,
  PRIMARY KEY (`Id_Cine`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pelicula` (
  `Id_Pelicula` INT NOT NULL,
  `Titulo` VARCHAR(255) NULL,
  `Genero` ENUM('Accion', 'Comedia', 'Terror', 'Crimen') NULL,
  `Duracion` INT NULL,
  `Sinopsis` VARCHAR(400) NULL,
  `Director` VARCHAR(255) NULL,
  `Anio_Lanzamiento` DATE NULL,
  PRIMARY KEY (`Id_Pelicula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resena` (
  `Id_Resena` INT NOT NULL,
  `Autor` VARCHAR(45) NULL,
  `Fecha` DATE NULL,
  `Puntuacion` DOUBLE NULL,
  `Texto` VARCHAR(455) NULL,
  `pelicula_Id_Pelicula` INT NOT NULL,
  PRIMARY KEY (`Id_Resena`),
  INDEX `fk_resena_pelicula1_idx` (`pelicula_Id_Pelicula` ASC) VISIBLE,
  CONSTRAINT `fk_resena_pelicula1`
    FOREIGN KEY (`pelicula_Id_Pelicula`)
    REFERENCES `mydb`.`pelicula` (`Id_Pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sala` (
  `Id_Sala` INT NOT NULL,
  `Capacidad` INT NULL,
  `Tipo` ENUM('3D', 'VIP', 'Normal') NULL,
  `Precio` INT NULL,
  `cine_Id_Cine` INT NOT NULL,
  PRIMARY KEY (`Id_Sala`, `cine_Id_Cine`),
  INDEX `fk_sala_cine1_idx` (`cine_Id_Cine` ASC) VISIBLE,
  CONSTRAINT `fk_sala_cine1`
    FOREIGN KEY (`cine_Id_Cine`)
    REFERENCES `mydb`.`cine` (`Id_Cine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actor_actua_pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actor_actua_pelicula` (
  `actor_Id_Actor` INT NOT NULL,
  `pelicula_Id_Pelicula` INT NOT NULL,
  PRIMARY KEY (`actor_Id_Actor`, `pelicula_Id_Pelicula`),
  INDEX `fk_actor_has_pelicula_pelicula1_idx` (`pelicula_Id_Pelicula` ASC) VISIBLE,
  INDEX `fk_actor_has_pelicula_actor_idx` (`actor_Id_Actor` ASC) VISIBLE,
  CONSTRAINT `fk_actor_has_pelicula_actor`
    FOREIGN KEY (`actor_Id_Actor`)
    REFERENCES `mydb`.`actor` (`Id_Actor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actor_has_pelicula_pelicula1`
    FOREIGN KEY (`pelicula_Id_Pelicula`)
    REFERENCES `mydb`.`pelicula` (`Id_Pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyeccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyeccion` (
  `Id_Proyeccion` INT NOT NULL,
  `sala_Id_Sala` INT NOT NULL,
  `sala_cine_Id_Cine` INT NOT NULL,
  `pelicula_Id_Pelicula` INT NOT NULL,
  `Fecha_Proyeccion` DATE NULL,
  `Hora_Proyeccion` ENUM('15:00', '17:30', ' 21:00') NULL,
  PRIMARY KEY (`Id_Proyeccion`, `sala_Id_Sala`, `sala_cine_Id_Cine`),
  INDEX `fk_proyeccion_sala1_idx` (`sala_Id_Sala` ASC, `sala_cine_Id_Cine` ASC) VISIBLE,
  INDEX `fk_proyeccion_pelicula1_idx` (`pelicula_Id_Pelicula` ASC) VISIBLE,
  CONSTRAINT `fk_proyeccion_sala1`
    FOREIGN KEY (`sala_Id_Sala` , `sala_cine_Id_Cine`)
    REFERENCES `mydb`.`sala` (`Id_Sala` , `cine_Id_Cine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyeccion_pelicula1`
    FOREIGN KEY (`pelicula_Id_Pelicula`)
    REFERENCES `mydb`.`pelicula` (`Id_Pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
